### ISSUE TITLE
Deeply nested package-subpackage-subsubpackage structure

### ISSUE THREAD

**Issue by bangconghuynh** [rdb/sphinx-autopackagesummary#1]
Hello,

This is a lovely extension! However, I am having problems with recursive generation. I have a package that has a rather deeply nested structure, like so:

```
package
  ├──sub-package1
  │     ├──subsub-package1
  │     │      ├──module1
  │     │      └──module2
  │     ├──subsub-package2
  │     └──subsub-package3
  └──sub-package2
         ├──module3
         └──module4
```

The documentations for `module3` and `module4` show up properly. `subsub-package1`, `subsub-package2`, and `subsub-package3` also show up in the summary table for `sub-package1`. However, `module1` and `module2` do not show up at all in the page for `subsub-package1`. In fact, no `.rst` files are generated for these modules at all.

I tried to get around this by adding the following line

```:template: autosummary/package.rst```

to the `package.rst` template file to allow the recursion to go as deep as possible. This almost worked in the sense that `.rst` files were generated for `module1` and `module2`. However, the `.rst` files for all modules (1, 2, 3, and 4) now also included an `..autopackagesummary` directive, which is not correct and which made Sphinx fail to compile. If I removed these manually, then every worked fine.

I am wondering if there is a way around this? Thanks very much!

**Comment by rdb** [comment]
Thanks for trying this extension!  Consider being the first person to star this repo. ;-)

I think the easiest way for me to fix this would be if `autopackagesummary` simply acted as though you specified an empty autosummary if it is passed the name of a module instead of a package.  That way, it will not do harm if the `module1.rst` file contains an `autopackagesummary` directive.

If you agree with this solution, I will implement this.  Otherwise, other suggestions for how to handle this are welcome.

**Comment by bangconghuynh** [comment]
Thanks for writing this extension! I can see that it's going to be a tremendous help for documenting packages with deep structures!

I think your proposed solution sounds simple enough and should work! I will be happy to test it once it's available.

Just another minor suggestion for `README.md`: the extension name should be `sphinx_autopackagesummary` instead of `autopackagesummary`. The latter gave me an `Extension error` at the beginning.

**Comment by rdb** [comment]
Thanks, all that should be fixed and it should not longer produce an error if a module is specified to autopackagesummary.  I've uploaded v1.2 to PyPI.  Let me know if you have further trouble.

I will consider if there may be more elegant ways to support dynamic nesting without requiring a custom template.

**Comment by bangconghuynh** [comment]
It works beautifully now, thank you for the fix! I suppose the content of `_templates/autosummary/package.rst` should be
```
{{ fullname | escape | underline }}

.. automodule:: {{ fullname }}

   .. autopackagesummary:: {{ fullname }}
      :toctree: .
      :template: autosummary/package.rst
```
to allow the recursion to go deep. The current `README.md` just misses out the `:template: autosummary/package.rst` bit.

I am happy with using a custom template to support dynamic nesting at the moment, but I agree that a native implementation of this within the extension itself would be a useful feature to have in future releases. Nevertheless, a custom template allows for quite a lot of flexibility for customisation of the summary pages for the subpackages, subsubpackages, and so on, so I think it is still very nice and useful!
