### ISSUE TITLE
Some modules not found on first pass

### ISSUE THREAD

**Issue by JamesALeedham** [rdb/sphinx-autopackagesummary#3]
Hi, this extension is absolutely brilliant. It is in the process of transforming how we generate API doc - thanks so much!

I have a rather disconcerting issue though. I've tested this separately on three large, heavily nested packages, and I can reproduce it reliably. For each, it fails to find at least one module each time. I get an error like this from autosummary:

`WARNING: Failed to import markovflow.kalman_filter: cannot import name 'KalmanFilter' from 'markovflow.kalman_filter' (/home/user/git/main/Platform_Learning/markovflow/markovflow/kalman_filter.py)`

...and then this one at the end when there's consequently nothing to insert in the toctree:

`/home/user/git/main/Platform_Learning/markovflow/docs/source/api.rst.rst:13: WARNING: autosummary: stub file not found 'markovflow.kalman_filter'. Check your autosummary_generate setting`

It's always the same module(s) in each project. There's nothing wrong with the import statements in the files.

I know this because there's a workaround - if I remove the `build/html` directory and run `make html` again then it magically finds the 'missing' modules, creates the `.rst` files, and correctly generates the html. So in other words running `make html; rm -rf build; make html` from the `docs` directory works perfectly, every time. It *is* a little cumbersome though (and a hard sell to some of the developers!)

Two of these projects are private but one is public: https://github.com/GPflow/GPflow. If you're interested then I can provide some commands to get you up and running, and the `conf.py` and `index.rst` files I'm using to generate the doc. Thanks!

**Comment by rdb** [comment]
Please do send me the files and instructions needed to reproduce this, thanks!

**Comment by JamesALeedham** [comment]
OK, great, thanks a lot. Here are the commands that work for me using Ubuntu 18.04 and Python 3.7.5 - I'm sure you can transcribe if you have a different environment.
```
git clone https://github.com/GPflow/GPflow.git
pip install -U pip #Needed to get the latest Tensorflow
pip install -e .
cd doc
pip install -r requirements.txt
pip install -U sphinx gast
pip install sphinx-autopackagesummary
```
If you then take the attached files and:

- Copy `index.rst` and `conf.py` into the `doc/source` directory, overwriting the originals.
- Copy `api.rst` into the `doc/source` directory.
- Copy `class.rst` and `module.rst` into the `doc/source/_template` directory.

Then, in the `doc` directory, run `make html`.

There's lots of rST warnings - we have some work to do on our formatting! There's also some warnings about missing Jupyter Notebooks which you can safely ignore. Right at the top are the missing modules errors:
```
WARNING: Failed to import gpflow.base: cannot import name 'Module' from 'gpflow.base' (/home/james.leedham/git/TEMP/GPflow/gpflow/base.py)
WARNING: Failed to import gpflow.conditionals: cannot import name 'conditional' from 'gpflow.conditionals' (/home/james.leedham/git/TEMP/GPflow/gpflow/conditionals/__init__.py)
WARNING: Failed to import gpflow.models: cannot import name 'BayesianModel' from 'gpflow.models' (/home/james.leedham/git/TEMP/GPflow/gpflow/models/__init__.py)
```
Weirdly, running `rm -rf build` and then `make html` finds and builds all 3 fine second time round...

[gpflow-files.zip](https://github.com/rdb/sphinx-autopackagesummary/files/4606213/gpflow-files.zip)

**Comment by rdb** [comment]
Hmm, yes, that *is* bizarre.  I wonder which cache files need to be deleted to recreate this.

**Comment by rdb** [comment]
It actually looks like #2 (which I had forgotten to look at) fixes this issue, so I'll merge that down and cut a new release.

**Comment by rdb** [comment]
I've just published version 1.3 of the package, please verify that the issue is fixed there.

**Comment by JamesALeedham** [comment]
That might have done the trick! Running version 1.3 over all three of my projects seems to generate them successfully first time. Not quite sure how the changes in #2 made that possible, but very happy that they do! Rock star!

I'll let you know if I have any more problems.

PS. Do you have an idea whether these forthcoming changes in Sphinx 3.1 are intending to replicate `sphinx-autopackagesummary` functionality..? (it's such an obvious shortcoming in `autosummary`...)

From https://www.sphinx-doc.org/en/master/usage/extensions/autosummary.html: "You can specify the recursive option to generate documents for modules and sub-packages recursively. It defaults to disabled. For example:"
```
.. autosummary::
   :recursive:

   sphinx.environment.BuildEnvironment
```
It's new in version 3.1 apparently. I thought I could get hold of version 3.1 by running `pip install -U --pre sphinx` but that doesn't seem to work for me...

**Comment by rdb** [comment]
Ah, that might make this package obsolete.  I'll keep an eye on that.

**Comment by JamesALeedham** [comment]
Hey @rdb, Sphinx 3.1 is out and `:recursive:` does work as the name suggests: https://stackoverflow.com/a/62613202/12014259

**Comment by rdb** [comment]
I'm giving it a try but I can't seem to make it pick up extension modules in my package.  If I can get it to work then I'll retire this package.
