### ISSUE TITLE
How to skip a module

### ISSUE THREAD

**Issue by JamesALeedham** [rdb/sphinx-autopackagesummary#4]
Hi @rdb, is there a way to skip a module? If I have a package structure like this:
```
mypackage
|__ module1
|__ module_to_exclude
|__ module2
```
...is there an easy way to **not** generate `mypackage.module_to_exclude.rst`? 

I tried using using the `autodoc-skip-member` callback in `conf.py` ([which now works](https://github.com/sphinx-doc/sphinx/issues/6798) with `sphinx.ext.autosummary`)... this code successfully excludes `myFunction` and `myClass`, but not `myModule`:
```
def setup(app):
    app.connect("autodoc-skip-member", autodoc_skip_member_callback)

def autodoc_skip_member_callback(app, what, name, obj, skip, options):
    exclusions = ('myFunction', 'myClass', 'myModule')
    exclude = name in exclusions
    return skip or exclude
```
I guess that makes sense as the native way to exclude a module using `sphinx.ext.autosummary` is just not to hard-code it in the list to begin with...

**Comment by rdb** [comment]
You can add it to `autosummary_mock_imports`:
```python
autosummary_mock_imports = [
    'mypackage.module_to_exclude',
]
```

Does this address your need?

**Comment by JamesALeedham** [comment]
Yes, that works, thanks!  

I saw you mentioned `autosummary_mock_imports` in the README but thought that setting did something else entirely... perhaps it's supposed to.

Not sure why, but adding `autosummary_mock_imports` to `conf.py` makes html build time go out from a tens of seconds to about 20 minutes. Painful.

**Comment by rdb** [comment]
That's odd.  The value defaults to `autodoc_mock_imports`, perhaps by adding `autosummary_mock_imports`, you have overridden the defaults that were specified in that setting?

**Comment by JamesALeedham** [comment]
Hmm, I suspect it's due to the complicated architectural structure of the production project I'm running Sphinx over... my simple test project works fine...  anyway, I can work round it, thanks for your help!
